Country: Tunisia
Coordinates:
  latitude: [30.24, 37.54]
  longitude: [7.52, 11.60]
Networks:
  2G:
    Rows: 3
    Columns: 1
    LocationNames:
      - nord
      - centre
      - sud
  3G:
    Rows: 3
    Columns: 1
    LocationNames:
      - nord
      - centre
      - sud
  4G:
    Rows: 3
    Columns: 2
    LocationNames:
      - nord-east
      - nord-west
      - centre-east
      - centre-west
      - sud-east
      - sud-west
customer:
  msisdn:
    home:
      country_code: "+216"
      ndc_ranges:
        - [30, 35]
        - [50, 55]
      digits: 6
      count: 1000
    national:
      country_code: "+216"
      ndc_ranges:
        - [20, 29]
        - [90, 99]
      digits: 6
      count: 1000
    international:
      prefixes: ["+2126", "+336", "+441", "+491"]
      digits: 8
      count: 100
      
