Locations:
  Latitude: [30.24, 37.54]
  Longitude: [7.52, 11.60]
  LocationSplit:
    - NetworkTechnology: 2G
      SplitRows: 3
      SplitColumns: 1
      LocationNames:
        - nord
        - centre
        - sud
    - NetworkTechnology: 3G
      SplitRows: 3
      SplitColumns: 1
      LocationNames:
        - nord
        - centre
        - sud
    - NetworkTechnology: 4G
      SplitRows: 3
      SplitColumns: 2
      LocationNames:
        - nord-east
        - nord-west
        - centre-east
        - centre-west
        - sud-east
        - sud-west
