services:
  postgis:
    image: postgis/postgis:18-3.6
    container_name: database-service
    environment:
      POSTGRES_DB: ev_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ev_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - osm_network

  osm2pgsql:
    image: overv/openstreetmap-tile-server:latest
    container_name: osm2pgsql
    depends_on:
      postgis:
        condition: service_healthy
    environment:
      UPDATES: disabled
      PGPASSWORD: password
    volumes:
      - ./osm:/osm
    networks:
      - osm_network
    command: >
      bash -c "
        echo 'Waiting for PostGIS...' &&
        until pg_isready -h postgis -U postgres -d ev_db; do
          sleep 3;
        done &&
        echo 'Starting import...' &&
        osm2pgsql -H postgis -U postgres -d ev_db -S /usr/share/osm2pgsql/default.style /osm/map.osm.pbf
      "

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dbadmin-service
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      postgis:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always
    networks:
      - osm_network

volumes:
  postgis_data:
  pgadmin_data:

networks:
  osm_network:
    driver: bridge
