version: '3.8'

services:
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter-ds
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: unless-stopped
