services:
  jupyter:
    build:
      context: .
    ports:
      - 8889:8888
    env_file:
      - ./../.env
    volumes:
      - ./notebooks:/home/jovyan/work
    command: start-notebook.py --NotebookApp.token='my-token'
