AWS_CONFIG = {
    "Regions": [
        {
            "Endpoint": "ec2.ap-south-2.amazonaws.com",
            "RegionName": "ap-south-2",
            "OptInStatus": "not-opted-in",
        },
        {
            "Endpoint": "ec2.ap-south-1.amazonaws.com",
            "RegionName": "ap-south-1",
            "OptInStatus": "opt-in-not-required",
        },
        {
            "Endpoint": "ec2.eu-south-1.amazonaws.com",
            "RegionName": "eu-south-1",
            "OptInStatus": "not-opted-in",
        },
        {
            "Endpoint": "ec2.eu-south-2.amazonaws.com",
            "RegionName": "eu-south-2",
            "OptInStatus": "not-opted-in",
        },
        {
            "Endpoint": "ec2.me-central-1.amazonaws.com",
            "RegionName": "me-central-1",
            "OptInStatus": "not-opted-in",
        },
        {
            "Endpoint": "ec2.il-central-1.amazonaws.com",
            "RegionName": "il-central-1",
            "OptInStatus": "not-opted-in",
        },
        {
            "Endpoint": "ec2.ca-central-1.amazonaws.com",
            "RegionName": "ca-central-1",
            "OptInStatus": "opt-in-not-required",
        },
        {
            "Endpoint": "ec2.eu-central-1.amazonaws.com",
            "RegionName": "eu-central-1",
            "OptInStatus": "opt-in-not-required",
        },
        {
            "Endpoint": "ec2.eu-central-2.amazonaws.com",
            "RegionName": "eu-central-2",
            "OptInStatus": "not-opted-in",
        },
        {
            "Endpoint": "ec2.us-west-1.amazonaws.com",
            "RegionName": "us-west-1",
            "OptInStatus": "opt-in-not-required",
        },
        {
            "Endpoint": "ec2.us-west-2.amazonaws.com",
            "RegionName": "us-west-2",
            "OptInStatus": "opt-in-not-required",
        },
        {
            "Endpoint": "ec2.af-south-1.amazonaws.com",
            "RegionName": "af-south-1",
            "OptInStatus": "not-opted-in",
        },
        {
            "Endpoint": "ec2.eu-north-1.amazonaws.com",
            "RegionName": "eu-north-1",
            "OptInStatus": "opt-in-not-required",
        },
        {
            "Endpoint": "ec2.eu-west-3.amazonaws.com",
            "RegionName": "eu-west-3",
            "OptInStatus": "opt-in-not-required",
        },
        {
            "Endpoint": "ec2.eu-west-2.amazonaws.com",
            "RegionName": "eu-west-2",
            "OptInStatus": "opt-in-not-required",
        },
        {
            "Endpoint": "ec2.eu-west-1.amazonaws.com",
            "RegionName": "eu-west-1",
            "OptInStatus": "opt-in-not-required",
        },
        {
            "Endpoint": "ec2.ap-northeast-3.amazonaws.com",
            "RegionName": "ap-northeast-3",
            "OptInStatus": "opt-in-not-required",
        },
        {
            "Endpoint": "ec2.ap-northeast-2.amazonaws.com",
            "RegionName": "ap-northeast-2",
            "OptInStatus": "opt-in-not-required",
        },
        {
            "Endpoint": "ec2.me-south-1.amazonaws.com",
            "RegionName": "me-south-1",
            "OptInStatus": "not-opted-in",
        },
        {
            "Endpoint": "ec2.ap-northeast-1.amazonaws.com",
            "RegionName": "ap-northeast-1",
            "OptInStatus": "opt-in-not-required",
        },
        {
            "Endpoint": "ec2.sa-east-1.amazonaws.com",
            "RegionName": "sa-east-1",
            "OptInStatus": "opt-in-not-required",
        },
        {
            "Endpoint": "ec2.ap-east-1.amazonaws.com",
            "RegionName": "ap-east-1",
            "OptInStatus": "not-opted-in",
        },
        {
            "Endpoint": "ec2.ca-west-1.amazonaws.com",
            "RegionName": "ca-west-1",
            "OptInStatus": "not-opted-in",
        },
        {
            "Endpoint": "ec2.ap-southeast-1.amazonaws.com",
            "RegionName": "ap-southeast-1",
            "OptInStatus": "opt-in-not-required",
        },
        {
            "Endpoint": "ec2.ap-southeast-2.amazonaws.com",
            "RegionName": "ap-southeast-2",
            "OptInStatus": "opt-in-not-required",
        },
        {
            "Endpoint": "ec2.ap-southeast-3.amazonaws.com",
            "RegionName": "ap-southeast-3",
            "OptInStatus": "not-opted-in",
        },
        {
            "Endpoint": "ec2.ap-southeast-4.amazonaws.com",
            "RegionName": "ap-southeast-4",
            "OptInStatus": "not-opted-in",
        },
        {
            "Endpoint": "ec2.us-east-1.amazonaws.com",
            "RegionName": "us-east-1",
            "OptInStatus": "opt-in-not-required",
        },
        {
            "Endpoint": "ec2.us-east-2.amazonaws.com",
            "RegionName": "us-east-2",
            "OptInStatus": "opt-in-not-required",
        },
    ],
    "Services": [
        {"ServiceCode": "AWSCloudMap", "ServiceName": "AWS Cloud Map"},
        {"ServiceCode": "access-analyzer", "ServiceName": "Access Analyzer"},
        {"ServiceCode": "account", "ServiceName": "AWS Account Management"},
        {"ServiceCode": "acm", "ServiceName": "AWS Certificate Manager (ACM)"},
        {"ServiceCode": "acm-pca", "ServiceName": "AWS Private Certificate Authority"},
        {
            "ServiceCode": "airflow",
            "ServiceName": "Amazon Managed Workflows for Apache Airflow",
        },
        {"ServiceCode": "amplify", "ServiceName": "AWS Amplify"},
        {"ServiceCode": "amplifyuibuilder", "ServiceName": "Amplify UI Builder"},
        {"ServiceCode": "aoss", "ServiceName": "Amazon OpenSearch Serverless"},
        {"ServiceCode": "apigateway", "ServiceName": "Amazon API Gateway"},
        {
            "ServiceCode": "app-integrations",
            "ServiceName": "Amazon Connect Application Integrations",
        },
        {"ServiceCode": "appconfig", "ServiceName": "AWS AppConfig"},
        {"ServiceCode": "appfabric", "ServiceName": "AWS AppFabric"},
        {"ServiceCode": "appflow", "ServiceName": "Amazon AppFlow"},
        {
            "ServiceCode": "application-autoscaling",
            "ServiceName": "Application Auto Scaling",
        },
        {
            "ServiceCode": "application-cost-profiler",
            "ServiceName": "AWS Application Cost Profiler",
        },
        {"ServiceCode": "appmesh", "ServiceName": "AWS App Mesh"},
        {"ServiceCode": "apprunner", "ServiceName": "AWS App Runner"},
        {"ServiceCode": "appstream2", "ServiceName": "Amazon AppStream 2.0"},
        {"ServiceCode": "appsync", "ServiceName": "AWS AppSync"},
        {"ServiceCode": "aps", "ServiceName": "Amazon Managed Prometheus"},
        {"ServiceCode": "athena", "ServiceName": "Amazon Athena"},
        {"ServiceCode": "auditmanager", "ServiceName": "AWS Audit Manager"},
        {"ServiceCode": "autoscaling", "ServiceName": "Amazon EC2 Auto Scaling"},
        {"ServiceCode": "autoscaling-plans", "ServiceName": "AWS Auto Scaling Plans"},
        {
            "ServiceCode": "aws-marketplace",
            "ServiceName": "AWS Marketplace Deployment Service",
        },
        {"ServiceCode": "b2bi", "ServiceName": "B2B Data Interchange"},
        {"ServiceCode": "backup", "ServiceName": "AWS Backup"},
        {"ServiceCode": "batch", "ServiceName": "AWS Batch"},
        {
            "ServiceCode": "bcm-data-exports",
            "ServiceName": "AWS Billing And Cost Management Data Exports",
        },
        {"ServiceCode": "bedrock", "ServiceName": "Amazon Bedrock"},
        {
            "ServiceCode": "bedrock-evaluation",
            "ServiceName": "Amazon Bedrock Evaluation",
        },
        {"ServiceCode": "billingconductor", "ServiceName": "AWS Billing Conductor"},
        {"ServiceCode": "braket", "ServiceName": "Amazon Braket"},
        {"ServiceCode": "bugbust", "ServiceName": "AWS Bugbust"},
        {"ServiceCode": "cases", "ServiceName": "Amazon Connect Cases"},
        {
            "ServiceCode": "cassandra",
            "ServiceName": "Amazon Keyspaces (for Apache Cassandra)",
        },
        {"ServiceCode": "ce", "ServiceName": "AWS Cost Explorer"},
        {"ServiceCode": "chatbot", "ServiceName": "AWS Chatbot"},
        {"ServiceCode": "chime", "ServiceName": "Amazon Chime"},
        {"ServiceCode": "cleanrooms", "ServiceName": "AWS Clean Rooms"},
        {"ServiceCode": "cleanrooms-ml", "ServiceName": "AWS Clean Rooms ML"},
        {"ServiceCode": "cloud9", "ServiceName": "AWS Cloud9"},
        {"ServiceCode": "cloudformation", "ServiceName": "AWS CloudFormation"},
        {"ServiceCode": "cloudfront", "ServiceName": "Amazon CloudFront"},
        {"ServiceCode": "cloudhsm", "ServiceName": "AWS CloudHSM"},
        {"ServiceCode": "cloudshell", "ServiceName": "AWS CloudShell"},
        {"ServiceCode": "cloudtrail", "ServiceName": "AWS CloudTrail"},
        {"ServiceCode": "codeartifact", "ServiceName": "AWS CodeArtifact"},
        {"ServiceCode": "codebuild", "ServiceName": "AWS CodeBuild"},
        {"ServiceCode": "codecommit", "ServiceName": "AWS CodeCommit"},
        {"ServiceCode": "codedeploy", "ServiceName": "AWS CodeDeploy"},
        {"ServiceCode": "codeguru-profiler", "ServiceName": "Amazon CodeGuru Profiler"},
        {"ServiceCode": "codeguru-reviewer", "ServiceName": "Amazon CodeGuru Reviewer"},
        {"ServiceCode": "codepipeline", "ServiceName": "AWS CodePipeline"},
        {
            "ServiceCode": "cognito-identity",
            "ServiceName": "Amazon Cognito Federated Identities",
        },
        {"ServiceCode": "cognito-idp", "ServiceName": "Amazon Cognito User Pools"},
        {"ServiceCode": "cognito-sync", "ServiceName": "Amazon Cognito Sync"},
        {"ServiceCode": "comprehend", "ServiceName": "Amazon Comprehend"},
        {
            "ServiceCode": "comprehendmedical",
            "ServiceName": "Amazon Comprehend Medical",
        },
        {"ServiceCode": "compute-optimizer", "ServiceName": "AWS Compute Optimizer"},
        {"ServiceCode": "config", "ServiceName": "AWS Config"},
        {"ServiceCode": "connect", "ServiceName": "Amazon Connect"},
        {
            "ServiceCode": "connect-campaigns",
            "ServiceName": "Amazon Connect outbound campaigns",
        },
        {"ServiceCode": "controltower", "ServiceName": "AWS Control Tower"},
        {
            "ServiceCode": "crowdscale-usagelimitservice",
            "ServiceName": "Mechanical Turk",
        },
        {"ServiceCode": "databrew", "ServiceName": "AWS Glue DataBrew"},
        {"ServiceCode": "dataexchange", "ServiceName": "AWS Data Exchange"},
        {"ServiceCode": "datapipeline", "ServiceName": "AWS Data Pipeline"},
        {"ServiceCode": "datasync", "ServiceName": "AWS DataSync"},
        {"ServiceCode": "datazone", "ServiceName": "Amazon DataZone"},
        {"ServiceCode": "dax", "ServiceName": "Amazon DynamoDB Accelerator (DAX)"},
        {"ServiceCode": "deadline", "ServiceName": "AWS Deadline Cloud"},
        {"ServiceCode": "deepracer", "ServiceName": "AWS DeepRacer"},
        {"ServiceCode": "directconnect", "ServiceName": "AWS Direct Connect"},
        {
            "ServiceCode": "discovery",
            "ServiceName": "AWS Application Discovery Service",
        },
        {"ServiceCode": "dlm", "ServiceName": "Amazon Data Lifecycle Manager"},
        {
            "ServiceCode": "dms",
            "ServiceName": "AWS Database Migration Service (AWS DMS)",
        },
        {
            "ServiceCode": "docdb",
            "ServiceName": "Amazon DocumentDB (with MongoDB compatibility)",
        },
        {
            "ServiceCode": "docdb-elastic",
            "ServiceName": "Amazon DocumentDB Elastic Clusters",
        },
        {"ServiceCode": "drs", "ServiceName": "ElasticDisasterRecovery"},
        {"ServiceCode": "ds", "ServiceName": "AWS Directory Service"},
        {"ServiceCode": "dynamodb", "ServiceName": "Amazon DynamoDB"},
        {
            "ServiceCode": "ebs",
            "ServiceName": "Amazon Elastic Block Store (Amazon EBS)",
        },
        {
            "ServiceCode": "ec2",
            "ServiceName": "Amazon Elastic Compute Cloud (Amazon EC2)",
        },
        {"ServiceCode": "ec2-ipam", "ServiceName": "IPAM"},
        {"ServiceCode": "ec2fastlaunch", "ServiceName": "EC2 Fast Launch"},
        {
            "ServiceCode": "ecr",
            "ServiceName": "Amazon Elastic Container Registry (Amazon ECR)",
        },
        {
            "ServiceCode": "ecr-public",
            "ServiceName": "Amazon Elastic Container Registry Public (Amazon ECR Public)",
        },
        {
            "ServiceCode": "ecs",
            "ServiceName": "Amazon Elastic Container Service (Amazon ECS)",
        },
        {
            "ServiceCode": "eks",
            "ServiceName": "Amazon Elastic Kubernetes Service (Amazon EKS)",
        },
        {"ServiceCode": "elastic-inference", "ServiceName": "Amazon Elastic Inference"},
        {"ServiceCode": "elasticache", "ServiceName": "Amazon ElastiCache"},
        {"ServiceCode": "elasticbeanstalk", "ServiceName": "AWS Elastic Beanstalk"},
        {
            "ServiceCode": "elasticfilesystem",
            "ServiceName": "Amazon Elastic File System (EFS)",
        },
        {
            "ServiceCode": "elasticloadbalancing",
            "ServiceName": "Elastic Load Balancing (ELB)",
        },
        {"ServiceCode": "elasticmapreduce", "ServiceName": "Amazon EMR"},
        {
            "ServiceCode": "elastictranscoder",
            "ServiceName": "Amazon Elastic Transcoder",
        },
        {"ServiceCode": "emr-serverless", "ServiceName": "Amazon EMR Serverless"},
        {"ServiceCode": "entityresolution", "ServiceName": "AWS Entity Resolution"},
        {"ServiceCode": "es", "ServiceName": "Amazon OpenSearch Service"},
        {
            "ServiceCode": "events",
            "ServiceName": "Amazon EventBridge (CloudWatch Events)",
        },
        {"ServiceCode": "evidently", "ServiceName": "Amazon CloudWatch Evidently"},
        {"ServiceCode": "fargate", "ServiceName": "AWS Fargate"},
        {"ServiceCode": "finspace", "ServiceName": "Amazon FinSpace"},
        {"ServiceCode": "firehose", "ServiceName": "Amazon Kinesis Data Firehose"},
        {"ServiceCode": "fis", "ServiceName": "AWS Fault Injection Service (FIS)"},
        {"ServiceCode": "fms", "ServiceName": "AWS Firewall Manager"},
        {"ServiceCode": "forecast", "ServiceName": "Amazon Forecast"},
        {"ServiceCode": "frauddetector", "ServiceName": "Amazon Fraud Detector"},
        {"ServiceCode": "fsx", "ServiceName": "Amazon FSx"},
        {"ServiceCode": "gamelift", "ServiceName": "Amazon GameLift"},
        {
            "ServiceCode": "geo",
            "ServiceName": "Amazon Location Service (Amazon Location)",
        },
        {"ServiceCode": "glacier", "ServiceName": "Amazon Glacier"},
        {"ServiceCode": "globalaccelerator", "ServiceName": "AWS Global Accelerator"},
        {"ServiceCode": "glue", "ServiceName": "AWS Glue"},
        {"ServiceCode": "grafana", "ServiceName": "Amazon Managed Grafana"},
        {"ServiceCode": "greengrass", "ServiceName": "AWS IoT Greengrass"},
        {"ServiceCode": "groundstation", "ServiceName": "AWS Ground Station"},
        {"ServiceCode": "guardduty", "ServiceName": "Amazon GuardDuty"},
        {"ServiceCode": "healthlake", "ServiceName": "AWS HealthLake"},
        {
            "ServiceCode": "iam",
            "ServiceName": "AWS Identity and Access Management (IAM)",
        },
        {"ServiceCode": "imagebuilder", "ServiceName": "EC2 Image Builder"},
        {"ServiceCode": "inspector", "ServiceName": "Amazon Inspector Classic"},
        {"ServiceCode": "inspector2", "ServiceName": "Amazon Inspector"},
        {
            "ServiceCode": "internetmonitor",
            "ServiceName": "CloudWatch Internet Monitor",
        },
        {"ServiceCode": "iot", "ServiceName": "AWS IoT"},
        {"ServiceCode": "iot1click", "ServiceName": "AWS IoT 1-Click"},
        {"ServiceCode": "iotanalytics", "ServiceName": "AWS IoT Analytics"},
        {"ServiceCode": "iotcore", "ServiceName": "AWS IoT Core"},
        {
            "ServiceCode": "iotdeviceadvisor",
            "ServiceName": "AWS IoT Core Device Advisor",
        },
        {"ServiceCode": "iotevents", "ServiceName": "AWS IoT Events"},
        {"ServiceCode": "iotfleethub", "ServiceName": "AWS IoT Fleet Hub"},
        {"ServiceCode": "iotfleetwise", "ServiceName": "AWS IoT FleetWise"},
        {"ServiceCode": "iotsitewise", "ServiceName": "AWS IoT SiteWise"},
        {"ServiceCode": "iotthingsgraph", "ServiceName": "AWS IoT Things Graph"},
        {"ServiceCode": "iottwinmaker", "ServiceName": "AWS IoT TwinMaker"},
        {"ServiceCode": "iotwireless", "ServiceName": "AWS IoT Wireless"},
        {"ServiceCode": "ivs", "ServiceName": "Amazon Interactive Video Service"},
        {
            "ServiceCode": "ivschat",
            "ServiceName": "Amazon Interactive Video Service Chat",
        },
        {
            "ServiceCode": "kafka",
            "ServiceName": "Amazon Managed Streaming for Kafka (MSK)",
        },
        {
            "ServiceCode": "kafkaconnect",
            "ServiceName": "Managed Streaming for Kafka Connect",
        },
        {"ServiceCode": "kendra", "ServiceName": "Amazon Kendra"},
        {
            "ServiceCode": "kendra-ranking",
            "ServiceName": "Amazon Kendra Intelligent Ranking",
        },
        {"ServiceCode": "kinesis", "ServiceName": "Amazon Kinesis Data Streams"},
        {
            "ServiceCode": "kinesisanalytics",
            "ServiceName": "Amazon Managed Service for Apache Flink",
        },
        {"ServiceCode": "kinesisvideo", "ServiceName": "Amazon Kinesis Video Streams"},
        {"ServiceCode": "kms", "ServiceName": "AWS Key Management Service (AWS KMS)"},
        {"ServiceCode": "lakeformation", "ServiceName": "AWS Lake Formation"},
        {"ServiceCode": "lambda", "ServiceName": "AWS Lambda"},
        {"ServiceCode": "launchwizard", "ServiceName": "AWS Launch Wizard"},
        {"ServiceCode": "lex", "ServiceName": "Amazon Lex"},
        {"ServiceCode": "license-manager", "ServiceName": "AWS License Manager"},
        {
            "ServiceCode": "license-manager-linux-subscriptions",
            "ServiceName": "AWS License Manager Linux Subscriptions",
        },
        {
            "ServiceCode": "license-manager-user-subscriptions",
            "ServiceName": "AWS License Manager User Subscriptions",
        },
        {"ServiceCode": "lightsail", "ServiceName": "Amazon Lightsail"},
        {"ServiceCode": "logs", "ServiceName": "Amazon CloudWatch Logs"},
        {
            "ServiceCode": "lookoutequipment",
            "ServiceName": "Amazon Lookout for Equipment",
        },
        {"ServiceCode": "lookoutmetrics", "ServiceName": "Amazon Lookout for Metrics"},
        {"ServiceCode": "lookoutvision", "ServiceName": "Amazon Lookout for Vision"},
        {"ServiceCode": "m2", "ServiceName": "AWS Mainframe Modernization"},
        {"ServiceCode": "machinelearning", "ServiceName": "Amazon Machine Learning"},
        {"ServiceCode": "macie2", "ServiceName": "Amazon Macie"},
        {
            "ServiceCode": "managedblockchain",
            "ServiceName": "Amazon Managed Blockchain",
        },
        {
            "ServiceCode": "managedblockchain-query",
            "ServiceName": "Amazon Managed Blockchain Query",
        },
        {"ServiceCode": "mediaconnect", "ServiceName": "AWS Elemental MediaConnect"},
        {"ServiceCode": "mediaconvert", "ServiceName": "AWS Elemental MediaConvert"},
        {"ServiceCode": "medialive", "ServiceName": "AWS Elemental MediaLive"},
        {"ServiceCode": "mediapackage", "ServiceName": "AWS Elemental MediaPackage"},
        {
            "ServiceCode": "mediapackagev2",
            "ServiceName": "AWS Elemental MediaPackage v2",
        },
        {"ServiceCode": "mediastore", "ServiceName": "AWS Elemental MediaStore"},
        {"ServiceCode": "mediatailor", "ServiceName": "AWS Elemental MediaTailor"},
        {"ServiceCode": "medical-imaging", "ServiceName": "AWS Health Imaging"},
        {"ServiceCode": "mgn", "ServiceName": "Application Migration"},
        {
            "ServiceCode": "migrationhuborchestrator",
            "ServiceName": "Migration Hub Orchestrator",
        },
        {
            "ServiceCode": "migrationhubstrategy",
            "ServiceName": "Migration Hub Strategy Recommendations",
        },
        {"ServiceCode": "monitoring", "ServiceName": "Amazon CloudWatch"},
        {"ServiceCode": "monitron", "ServiceName": "Amazon Monitron"},
        {"ServiceCode": "mq", "ServiceName": "Amazon MQ"},
        {"ServiceCode": "neptune", "ServiceName": "Amazon Neptune"},
        {"ServiceCode": "neptune-graph", "ServiceName": "Amazon Neptune Analytics"},
        {"ServiceCode": "network-firewall", "ServiceName": "AWS Network Firewall"},
        {"ServiceCode": "networkinsights", "ServiceName": "Network Insights"},
        {"ServiceCode": "networkmanager", "ServiceName": "AWS Cloud WAN"},
        {
            "ServiceCode": "networkmonitor",
            "ServiceName": "Amazon CloudWatch Network Monitor",
        },
        {"ServiceCode": "nimble", "ServiceName": "Amazon Nimble Studio"},
        {"ServiceCode": "notifications", "ServiceName": "AWS User Notifications"},
        {
            "ServiceCode": "oam",
            "ServiceName": "Amazon CloudWatch Observability Access Manager",
        },
        {"ServiceCode": "omics", "ServiceName": "AWS HealthOmics"},
        {"ServiceCode": "opsworks", "ServiceName": "AWS OpsWorks Stacks"},
        {
            "ServiceCode": "opsworks-cm",
            "ServiceName": "AWS OpsWorks for Chef Automate and AWS OpsWorks for Puppet Enterprise",
        },
        {"ServiceCode": "organizations", "ServiceName": "AWS Organizations"},
        {"ServiceCode": "outposts", "ServiceName": "AWS Outposts"},
        {"ServiceCode": "panorama", "ServiceName": "AWS Panorama"},
        {
            "ServiceCode": "payment-cryptography",
            "ServiceName": "AWS Payment Cryptography",
        },
        {
            "ServiceCode": "pca-connector-ad",
            "ServiceName": "Private CA Connector for Active Directory",
        },
        {"ServiceCode": "personalize", "ServiceName": "Amazon Personalize"},
        {"ServiceCode": "pinpoint", "ServiceName": "Amazon Pinpoint"},
        {"ServiceCode": "polly", "ServiceName": "Amazon Polly"},
        {"ServiceCode": "private-networks", "ServiceName": "AWS Private 5G"},
        {"ServiceCode": "profile", "ServiceName": "Amazon Connect Customer Profiles"},
        {"ServiceCode": "proton", "ServiceName": "AWS Proton"},
        {"ServiceCode": "qbusiness", "ServiceName": "Amazon Q"},
        {"ServiceCode": "qldb", "ServiceName": "Amazon QLDB"},
        {"ServiceCode": "quicksight", "ServiceName": "Amazon QuickSight"},
        {"ServiceCode": "ram", "ServiceName": "AWS Resource Access Manager"},
        {"ServiceCode": "rbin", "ServiceName": "Amazon Recycle Bin"},
        {
            "ServiceCode": "rds",
            "ServiceName": "Amazon Relational Database Service (Amazon RDS)",
        },
        {"ServiceCode": "redshift", "ServiceName": "Amazon Redshift"},
        {
            "ServiceCode": "refactor-spaces",
            "ServiceName": "AWS Migration Hub Refactor Spaces",
        },
        {"ServiceCode": "rekognition", "ServiceName": "Amazon Rekognition"},
        {"ServiceCode": "resiliencehub", "ServiceName": "AWS Resilience Hub"},
        {"ServiceCode": "resource-explorer-2", "ServiceName": "AWS Resource Explorer"},
        {"ServiceCode": "resource-groups", "ServiceName": "AWS Resource Groups"},
        {"ServiceCode": "robomaker", "ServiceName": "AWS RoboMaker"},
        {"ServiceCode": "rolesanywhere", "ServiceName": "IAM Roles Anywhere"},
        {"ServiceCode": "route53", "ServiceName": "Amazon Route 53"},
        {"ServiceCode": "route53profiles", "ServiceName": "Route 53 Profiles"},
        {"ServiceCode": "route53resolver", "ServiceName": "Route 53 Resolver"},
        {"ServiceCode": "rum", "ServiceName": "Amazon CloudWatch RUM"},
        {
            "ServiceCode": "s3",
            "ServiceName": "Amazon Simple Storage Service (Amazon S3)",
        },
        {"ServiceCode": "s3-outposts", "ServiceName": "AWS S3 Outposts"},
        {"ServiceCode": "sagemaker", "ServiceName": "Amazon SageMaker"},
        {"ServiceCode": "scheduler", "ServiceName": "Amazon EventBridge Scheduler"},
        {"ServiceCode": "schemas", "ServiceName": "Amazon EventBridge Schema Registry"},
        {"ServiceCode": "scn", "ServiceName": "AWS Supply Chain"},
        {"ServiceCode": "sdb", "ServiceName": "Amazon SimpleDB"},
        {"ServiceCode": "secretsmanager", "ServiceName": "AWS Secrets Manager"},
        {"ServiceCode": "securityhub", "ServiceName": "AWS Security Hub"},
        {
            "ServiceCode": "serverlessrepo",
            "ServiceName": "AWS Serverless Application Repository",
        },
        {"ServiceCode": "servicecatalog", "ServiceName": "AWS Service Catalog"},
        {"ServiceCode": "servicequotas", "ServiceName": "Service Quotas"},
        {
            "ServiceCode": "ses",
            "ServiceName": "Amazon Simple Email Service(Amazon SES)",
        },
        {"ServiceCode": "shield", "ServiceName": "AWS Shield Advanced"},
        {"ServiceCode": "signer", "ServiceName": "AWS Signer"},
        {"ServiceCode": "simspaceweaver", "ServiceName": "AWS SimSpace Weaver"},
        {"ServiceCode": "sms", "ServiceName": "AWS Server Migration Service"},
        {
            "ServiceCode": "snow-device-management",
            "ServiceName": "AWS Snow Device Management",
        },
        {"ServiceCode": "snowball", "ServiceName": "AWS Snow Family"},
        {
            "ServiceCode": "sns",
            "ServiceName": "Amazon Simple Notification Service (Amazon SNS)",
        },
        {
            "ServiceCode": "sqs",
            "ServiceName": "Amazon Simple Queue Service (Amazon SQS)",
        },
        {"ServiceCode": "ssm", "ServiceName": "AWS Systems Manager"},
        {
            "ServiceCode": "ssm-contacts",
            "ServiceName": "AWS Systems Manager Incident Manager Contacts",
        },
        {
            "ServiceCode": "ssm-guiconnect",
            "ServiceName": "AWS Systems Manager GUI Connect",
        },
        {
            "ServiceCode": "ssm-incidents",
            "ServiceName": "AWS Systems Manager Incident Manager",
        },
        {"ServiceCode": "ssm-sap", "ServiceName": "AWS Systems Manager for SAP"},
        {
            "ServiceCode": "sso",
            "ServiceName": "AWS IAM Identity Center (successor to AWS Single Sign-On)",
        },
        {"ServiceCode": "states", "ServiceName": "AWS Step Functions"},
        {"ServiceCode": "storagegateway", "ServiceName": "AWS Storage Gateway"},
        {"ServiceCode": "support", "ServiceName": "AWS Support"},
        {"ServiceCode": "supportapp", "ServiceName": "AWS Support App"},
        {"ServiceCode": "swf", "ServiceName": "Amazon Simple Workflow Service"},
        {"ServiceCode": "textract", "ServiceName": "Amazon Textract"},
        {"ServiceCode": "timestream", "ServiceName": "Amazon Timestream"},
        {
            "ServiceCode": "timestream-influxdb",
            "ServiceName": "Amazon Timestream for Managed Influx",
        },
        {"ServiceCode": "tnb", "ServiceName": "AWS Telco Network Builder"},
        {"ServiceCode": "transcribe", "ServiceName": "Amazon Transcribe"},
        {"ServiceCode": "transfer", "ServiceName": "AWS Transfer Family"},
        {"ServiceCode": "translate", "ServiceName": "Amazon Translate"},
        {"ServiceCode": "trustedadvisor", "ServiceName": "AWS Trusted Advisor"},
        {"ServiceCode": "ts", "ServiceName": "Diagnostic Tools"},
        {
            "ServiceCode": "vendor-insights",
            "ServiceName": "AWS Marketplace Vendor Insights",
        },
        {
            "ServiceCode": "verifiedpermissions",
            "ServiceName": "Amazon Verified Permissions",
        },
        {"ServiceCode": "vmimportexport", "ServiceName": "EC2 VM Import/Export"},
        {"ServiceCode": "voiceid", "ServiceName": "Amazon Connect Voice ID"},
        {
            "ServiceCode": "vpc",
            "ServiceName": "Amazon Virtual Private Cloud (Amazon VPC)",
        },
        {"ServiceCode": "vpc-lattice", "ServiceName": "VPC Lattice"},
        {"ServiceCode": "waf", "ServiceName": "AWS WAF Classic (Global)"},
        {"ServiceCode": "waf-regional", "ServiceName": "AWS WAF Classic (Regional)"},
        {"ServiceCode": "wafv2", "ServiceName": "AWS WAF"},
        {"ServiceCode": "wam", "ServiceName": "Amazon WorkSpaces Application Manager"},
        {"ServiceCode": "wellarchitected", "ServiceName": "AWS Well-Architected Tool"},
        {"ServiceCode": "wisdom", "ServiceName": "Amazon Q in Connect"},
        {"ServiceCode": "workspaces", "ServiceName": "Amazon WorkSpaces"},
        {"ServiceCode": "workspaces-web", "ServiceName": "Amazon WorkSpaces Web"},
        {"ServiceCode": "xray", "ServiceName": "AWS X-Ray"},
    ],
}
