name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Format code
      run: |
        make format
    - name: Test
      run: |
        make test
    - name: Run
      run: |
        make run
    - name: Build
      run: |
        make build
